version: '3.1'

services:
  mongo:
    image: mongo:4.4
    restart: always
    command: mongod --serviceExecutor adaptive
    ports:
      - 1001:27017
    env_file: 
      - .env.dev
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
