version: '3.1'

services:
  postgress:
    image: postgres
    restart: always
    working_dir: /home/node/app
    env_file:
      - .env.dev
    ports:
      - 1000:5432
  mongo:
    image: mongo:4.4
    restart: always
    command: mongod --serviceExecutor adaptive
    ports:
      - 1001:27017
    env_file: 
      - .env.dev
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro