version: '3.1'

services:
  postgress:
    image: postgres
    restart: always
    working_dir: /home/node/app
    env_file:
      - .env.prod
  mongo:
    image: mongo:4.4
    restart: always
    command: mongod --serviceExecutor adaptive
    env_file: 
      - .env.test
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro